name: Build & Publish Release APK

on:
  push:
    branches:
      - stable
    tags:
      - "*"
  workflow_dispatch:

jobs:
  Gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "20"
          cache: "gradle"

      - name: Setup node
        uses: antongolub/action-setup-bun@v1 # or @v1.x.x
        with:
          bun-version: "1.0.25"
          cache: true
          cache-bin: true
          
      - name: Install dependencies
        run: bun install

      - name: Build Expo
        run: bun run build:android

      - name: Prepare Keystore
        shell: bash
        run: echo "${{ secrets.BASE_64_SIGNING_KEY }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks

      - name: Build Signed APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=key0 \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Prepare Tag
        id: tag
        run: echo "version=$(date +'v%y.%m.%d.%H%M%S')"  >> $GITHUB_OUTPUT

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/*.apk
          tag: ${{ steps.tag.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
